name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "KAFKA_INSTALL_PATH=/opt/kafka" >> $GITHUB_ENV
          echo "COFFEEZ_ROOT=./" >> $GITHUB_ENV

      - name: Run setup script
        run: bash scripts/setup_ubuntu.sh

      - name: Run start script
        run: bash scripts/start_all_services.sh start

      - name: Run stop script
        run: bash scripts/start_all_services.sh stop

      - name: Run reset script
        run: bash scripts/start_all_services.sh reset

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "KAFKA_INSTALL_PATH=/opt/kafka" >> $GITHUB_ENV
          echo "COFFEEZ_ROOT=./" >> $GITHUB_ENV

      - name: Run setup script
        run: bash scripts/setup_macos.sh

      - name: Run start script
        run: bash scripts/start_all_services.sh start

      - name: Run stop script
        run: bash scripts/start_all_services.sh stop

      - name: Run reset script
        run: bash scripts/start_all_services.sh reset 