name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COFFEEZ_PAT }}

      - name: Configure Git for private repos
        run: |
          git config --global url."https://${{ secrets.COFFEEZ_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Set up environment variables
        run: |
          echo "KAFKA_INSTALL_PATH=/opt/kafka" >> $GITHUB_ENV
          echo "COFFEEZ_ROOT=./" >> $GITHUB_ENV

      - name: Install Make
        run: |
          xcode-select --install || true
          brew install make

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Setup environment
        run: make setup

      - name: Start services
        run: make up

      - name: Check service logs
        run: |
          sleep 30  # Wait for services to start
          if grep -i "error\|fail\|exception" logs/*.log; then
            echo "Found errors in logs"
            exit 1
          fi

      - name: Stop services
        if: always()
        run: make down

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COFFEEZ_PAT }}

      - name: Configure Git for private repos
        run: |
          git config --global url."https://${{ secrets.COFFEEZ_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Set up environment variables
        run: |
          echo "KAFKA_INSTALL_PATH=/opt/kafka" >> $GITHUB_ENV
          echo "COFFEEZ_ROOT=./" >> $GITHUB_ENV

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Setup environment
        run: make setup

      - name: Start services
        run: make up

      - name: Check service logs
        run: |
          sleep 30  # Wait for services to start
          if grep -i "error\|fail\|exception" logs/*.log; then
            echo "Found errors in logs"
            exit 1
          fi

      - name: Stop services
        if: always()
        run: make down 